# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./001-init-user-db.sh:/docker-entrypoint-initdb.d/001-init-user-db.sh
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: example
      PGADMIN_DEFAULT_EMAIL: user@domain.com

  backend:
    image: krismt/nodemon
    volumes:
      - ./backend:/data
    ports:
      - 4000:4000


